apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZWEIxZEdsdWRITmxkanBuYUhCZldFYzNTRTF4V0RGTVkxZFFXVGh5YTNsbFZVeFZhRTlRTTJ4MmVXUkpNbVJMZFhOSSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
